---
kind: pipeline
type: docker
name: compile-m68k-000

steps:
- name: build
  pull: always
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.docker

---
kind: pipeline
type: docker
name: compile-m68k-030

steps:
- name: build
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.docker iGame.030

---
kind: pipeline
type: docker
name: compile-m68k-040

steps:
- name: build
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.docker iGame.040

---
kind: pipeline
type: docker
name: compile-m68k-060

steps:
- name: build
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.docker iGame.060

---
kind: pipeline
type: docker
name: compile-os4

steps:
- name: build
  pull: always
  image: walkero/docker4amigavbcc:latest-ppc
  commands:
    - cd /drone/src
    - make -f Makefile.docker iGame.OS4

---
kind: pipeline
type: docker
name: compile-mos

steps:
- name: build
  pull: always
  image: walkero/docker4amigavbcc:latest-mos
  commands:
    - cd /drone/src
    - make -f Makefile.docker iGame.MOS

---
kind: pipeline
type: docker
name: create-release-files

steps:
- name: notify
  image: plugins/slack
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.docker release

depends_on:
- compile-m68k-000
- compile-m68k-030
- compile-m68k-040
- compile-m68k-060
- compile-os4
- compile-mos

trigger:
  event:
    include:
    - push
